
import React, { useState, useMemo } from 'react';
import { Plus, Trash2, Save, ArrowLeft, Loader2, BookA, Search, Database } from 'lucide-react';
import { DictionaryEntry } from '../types';
import { supabase } from '../supabaseClient';
import { INITIAL_DICTIONARY } from '../constants';

interface GlossaryManagerProps {
  dictionary: DictionaryEntry[];
  onSave: () => void;
}

const GlossaryManager: React.FC<GlossaryManagerProps> = ({ dictionary, onSave }) => {
  const [view, setView] = useState<'list' | 'edit'>('list');
  const [currentEntry, setCurrentEntry] = useState<Partial<DictionaryEntry>>({});
  const [isSaving, setIsSaving] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');

  // Repair SQL in case table is missing or structure is wrong
  const repairSql = `
CREATE TABLE IF NOT EXISTS public.dictionary_shibari (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term text NOT NULL,
    definition text,
    term_en text,
    definition_en text,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.dictionary_shibari ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'dictionary_shibari' AND policyname = 'Allow all') THEN
    CREATE POLICY "Allow all" ON public.dictionary_shibari FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;
  `.trim();

  // Filter dictionary based on search
  const filteredDictionary = useMemo(() => {
      if (!searchQuery) return dictionary;
      const lowerQ = searchQuery.toLowerCase();
      return dictionary.filter(item => 
          item.term.toLowerCase().includes(lowerQ) || 
          (item.term_en && item.term_en.toLowerCase().includes(lowerQ))
      );
  }, [dictionary, searchQuery]);

  const handleSeed = async () => {
      if (!window.confirm("Загрузить базовый словарь? Это добавит термины из констант.")) return;
      setIsSaving(true);
      try {
          if (!supabase) throw new Error("No DB");
          const seedData = INITIAL_DICTIONARY.map(({ id, ...rest }) => rest);
          const { error } = await supabase.from('dictionary_shibari').insert(seedData);
          if (error) throw error;
          alert("Словарь загружен!");
          onSave();
      } catch (e: any) {
          console.error(e);
          alert(`Ошибка: ${e.message}\nSQL:\n${repairSql}`);
      } finally {
          setIsSaving(false);
      }
  };

  const startEdit = (entry?: DictionaryEntry) => {
    if (entry) {
      setCurrentEntry(entry);
    } else {
      setCurrentEntry({
        term: '',
        definition: '',
        term_en: '',
        definition_en: ''
      });
    }
    setView('edit');
  };

  const handleSave = async () => {
    if (!currentEntry.term) {
      alert("Термин обязателен");
      return;
    }

    setIsSaving(true);
    try {
      if (!supabase) throw new Error("No database connection");

      const payload = {
        term: currentEntry.term,
        definition: currentEntry.definition,
        term_en: currentEntry.term_en,
        definition_en: currentEntry.definition_en
      };

      if (currentEntry.id) {
        const { error } = await supabase
          .from('dictionary_shibari')
          .update(payload)
          .eq('id', currentEntry.id);
        if (error) throw error;
      } else {
        const { error } = await supabase
          .from('dictionary_shibari')
          .insert([payload]);
        if (error) throw error;
      }

      onSave();
      setView('list');
    } catch (e: any) {
      console.error(e);
      alert(`Ошибка сохранения: ${e.message}\nSQL:\n${repairSql}`);
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = async (id: number) => {
    if (!window.confirm("Удалить термин?")) return;
    try {
      if (supabase) {
        await supabase.from('dictionary_shibari').delete().eq('id', id);
        onSave();
      }
    } catch (e) {
      console.error(e);
    }
  };

  if (view === 'list') {
    return (
      <div className="space-y-6">
         <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 bg-neutral-900/50 p-4 rounded-xl border border-neutral-800">
            <div>
                <p className="text-white font-bold flex items-center gap-2"><BookA className="w-4 h-4"/> Глоссарий</p>
                <p className="text-neutral-500 text-sm">Всего терминов: {dictionary.length}</p>
            </div>
            
            <div className="flex flex-col md:flex-row gap-2 w-full md:w-auto">
                {/* Search */}
                <div className="relative">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-neutral-500" />
                    <input 
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        placeholder="Поиск..."
                        className="bg-neutral-950 border border-neutral-700 rounded-lg pl-9 pr-3 py-2 text-sm text-white outline-none focus:border-red-500 w-full md:w-48"
                    />
                </div>

                <div className="flex gap-2">
                    {dictionary.length === 0 && (
                        <button 
                            onClick={handleSeed}
                            disabled={isSaving}
                            className="bg-neutral-800 hover:bg-neutral-700 text-neutral-300 px-3 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors border border-neutral-700 text-xs uppercase"
                        >
                            {isSaving ? <Loader2 className="w-3 h-3 animate-spin"/> : <Database className="w-3 h-3" />} 
                            Демо
                        </button>
                    )}
                    <button 
                        onClick={() => startEdit()}
                        className="bg-red-700 hover:bg-red-600 text-white px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors text-sm w-full md:w-auto justify-center"
                    >
                        <Plus className="w-4 h-4" /> Добавить
                    </button>
                </div>
            </div>
        </div>

        <div className="space-y-3">
            {filteredDictionary.map(entry => (
                <div key={entry.id} className="bg-neutral-900 border border-neutral-800 p-4 rounded-xl flex flex-col md:flex-row md:items-center justify-between hover:border-neutral-700 transition-colors gap-4">
                    <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-3 mb-1">
                            <h4 className="font-bold text-white text-lg">{entry.term}</h4>
                            {entry.term_en && <span className="text-neutral-500 text-sm font-mono bg-neutral-950 px-2 py-0.5 rounded border border-neutral-800">{entry.term_en}</span>}
                        </div>
                        <p className="text-neutral-400 text-sm line-clamp-2">{entry.definition}</p>
                    </div>
                    <div className="flex gap-2 shrink-0">
                        <button onClick={() => startEdit(entry)} className="px-3 py-2 bg-neutral-800 hover:bg-neutral-700 text-white rounded-lg transition-colors text-sm">Ред.</button>
                        <button onClick={() => entry.id && handleDelete(entry.id)} className="px-3 py-2 bg-neutral-800 hover:bg-red-900/50 text-red-500 rounded-lg transition-colors"><Trash2 className="w-4 h-4"/></button>
                    </div>
                </div>
            ))}
            {filteredDictionary.length === 0 && (
                <div className="text-center text-neutral-600 py-10 border border-dashed border-neutral-800 rounded-xl">
                    {searchQuery ? 'Ничего не найдено' : 'Словарь пуст'}
                </div>
            )}
        </div>
      </div>
    );
  }

  // Edit Mode
  return (
    <div className="flex flex-col h-full space-y-6">
        <div className="flex items-center justify-between border-b border-neutral-800 pb-4">
             <button onClick={() => setView('list')} className="text-neutral-400 hover:text-white flex items-center gap-2 px-3 py-1 bg-neutral-800 rounded transition-colors">
                <ArrowLeft className="w-4 h-4" /> Назад
             </button>
             <button onClick={handleSave} disabled={isSaving} className="bg-green-700 hover:bg-green-600 text-white px-6 py-2 rounded-lg font-medium flex items-center gap-2 disabled:opacity-50 transition-colors shadow-lg shadow-green-900/20">
                {isSaving ? <Loader2 className="w-4 h-4 animate-spin"/> : <Save className="w-4 h-4" />} Сохранить
            </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Russian Column */}
            <div className="space-y-4 bg-neutral-900/30 p-6 rounded-xl border border-neutral-800">
                <div className="flex items-center gap-2 mb-2">
                    <span className="bg-red-900/30 text-red-500 text-xs font-bold px-2 py-1 rounded">RU</span>
                    <h3 className="text-white font-bold">Русский язык</h3>
                </div>
                
                <div className="space-y-2">
                    <label className="text-xs text-neutral-500 font-bold uppercase">Термин</label>
                    <input 
                        value={currentEntry.term || ''}
                        onChange={e => setCurrentEntry({...currentEntry, term: e.target.value})}
                        placeholder="Например: Уке"
                        className="w-full bg-neutral-900 border border-neutral-700 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none text-lg font-bold placeholder-neutral-700"
                    />
                </div>
                
                <div className="space-y-2">
                    <label className="text-xs text-neutral-500 font-bold uppercase">Определение</label>
                    <textarea 
                        value={currentEntry.definition || ''}
                        onChange={e => setCurrentEntry({...currentEntry, definition: e.target.value})}
                        rows={6}
                        placeholder="Описание термина..."
                        className="w-full bg-neutral-900 border border-neutral-700 rounded-lg px-4 py-3 text-white focus:border-red-600 outline-none resize-none leading-relaxed placeholder-neutral-700"
                    />
                </div>
            </div>

            {/* English Column */}
            <div className="space-y-4 bg-neutral-900/30 p-6 rounded-xl border border-neutral-800">
                <div className="flex items-center gap-2 mb-2">
                    <span className="bg-blue-900/30 text-blue-500 text-xs font-bold px-2 py-1 rounded">EN</span>
                    <h3 className="text-white font-bold">English (Optional)</h3>
                </div>

                <div className="space-y-2">
                    <label className="text-xs text-neutral-500 font-bold uppercase">Term (English)</label>
                    <input 
                        value={currentEntry.term_en || ''}
                        onChange={e => setCurrentEntry({...currentEntry, term_en: e.target.value})}
                        placeholder="e.g. Uke"
                        className="w-full bg-neutral-900 border border-neutral-700 rounded-lg px-4 py-3 text-white focus:border-blue-600 outline-none text-lg font-bold placeholder-neutral-700"
                    />
                </div>
                
                <div className="space-y-2">
                    <label className="text-xs text-neutral-500 font-bold uppercase">Definition (English)</label>
                    <textarea 
                        value={currentEntry.definition_en || ''}
                        onChange={e => setCurrentEntry({...currentEntry, definition_en: e.target.value})}
                        rows={6}
                        placeholder="English description..."
                        className="w-full bg-neutral-900 border border-neutral-700 rounded-lg px-4 py-3 text-white focus:border-blue-600 outline-none resize-none leading-relaxed placeholder-neutral-700"
                    />
                </div>
            </div>
        </div>
    </div>
  );
};

export default GlossaryManager;
