
import React, { useState } from 'react';
import { X, Settings, ShoppingBag, Video, FolderOpen, Calendar, Scroll, Link, FileText, ChevronDown, Wrench, BookA } from 'lucide-react';
import { Lesson, Product, Course, AppEvent, HistoryEvent, Article, CatalogCategory, CatalogVideo, DictionaryEntry } from '../types';
import { supabase } from '../supabaseClient';

import MarketplaceManager from './MarketplaceManager';
import CourseManager from './CourseManager';
import EventsManager from './EventsManager';
import HistoryManager from './HistoryManager';
import ArticleConstructor from './ArticleConstructor';
import CatalogManager from './CatalogManager';
import GlossaryManager from './GlossaryManager';

interface SettingsModalProps {
  isOpen: boolean;
  onClose: () => void;
  
  lessons: Lesson[];
  onUpdateLesson: (id: number, data: Partial<Lesson>) => void;

  products?: Product[];
  courses?: Course[];
  events?: AppEvent[];
  history?: HistoryEvent[];
  articles?: Article[];
  catalogCategories?: CatalogCategory[];
  catalogVideos?: CatalogVideo[];
  dictionary?: DictionaryEntry[];
  
  onRefresh?: () => void;
}

type AdminTab = 'general' | 'lessons' | 'articles' | 'shop' | 'courses' | 'catalog' | 'events' | 'history' | 'glossary';

const SettingsModal: React.FC<SettingsModalProps> = ({ 
    isOpen, onClose, lessons, onUpdateLesson,
    products = [], courses = [], events = [], history = [], articles = [], catalogCategories = [], catalogVideos = [], dictionary = [],
    onRefresh = () => {}
}) => {
  const [activeTab, setActiveTab] = useState<AdminTab>('lessons');

  const repairLessonsTable = async () => {
      if(!window.confirm("Это попытается создать/исправить таблицу уроков и добавить колонку related_articles. Продолжить?")) return;
      
      const sql = `
CREATE TABLE IF NOT EXISTS public.lessons_shibari (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text,
    video_url text,
    content text[],
    related_articles integer[] DEFAULT '{}',
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now())
);
ALTER TABLE public.lessons_shibari ADD COLUMN IF NOT EXISTS related_articles integer[] DEFAULT '{}';
ALTER TABLE public.lessons_shibari ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'lessons_shibari' AND policyname = 'Allow all') THEN
    CREATE POLICY "Allow all" ON public.lessons_shibari FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;
      `;
      alert("Пожалуйста, выполните этот SQL в панели Supabase, если кнопка не сработает (клиент не может менять схему напрямую если не админ базы):\n\n" + sql);
  };

  if (!isOpen) return null;

  const tabs: { id: AdminTab, label: string, icon: any }[] = [
      { id: 'lessons', label: 'Уроки', icon: Video },
      { id: 'articles', label: 'Статьи', icon: FileText },
      { id: 'glossary', label: 'Словарь', icon: BookA },
      { id: 'shop', label: 'Магазин', icon: ShoppingBag },
      { id: 'courses', label: 'Курсы', icon: Video },
      { id: 'catalog', label: 'Каталог', icon: FolderOpen },
      { id: 'events', label: 'Афиша', icon: Calendar },
      { id: 'history', label: 'История', icon: Scroll },
  ];

  return (
    <div className="fixed inset-0 z-[100] flex bg-black/95 backdrop-blur-md animate-in fade-in duration-200">
      
      {/* Sidebar Navigation */}
      <div className="w-20 md:w-64 bg-neutral-900 border-r border-neutral-800 flex flex-col shrink-0">
          <div className="p-6 border-b border-neutral-800 flex items-center gap-3">
              <div className="w-8 h-8 bg-red-600 rounded-lg flex items-center justify-center shrink-0">
                  <Settings className="w-5 h-5 text-white" />
              </div>
              <span className="font-bold text-white text-lg hidden md:block">Admin Hub</span>
          </div>
          
          <nav className="flex-1 p-2 space-y-1 overflow-y-auto">
              {tabs.map(tab => (
                  <button
                      key={tab.id}
                      onClick={() => setActiveTab(tab.id)}
                      className={`w-full flex items-center gap-3 px-3 py-3 rounded-xl transition-all ${
                          activeTab === tab.id 
                          ? 'bg-red-900/20 text-red-500 border border-red-900/50' 
                          : 'text-neutral-400 hover:bg-neutral-800 hover:text-white'
                      }`}
                  >
                      <tab.icon className={`w-5 h-5 ${activeTab === tab.id ? 'fill-current' : ''}`} />
                      <span className="font-medium hidden md:block">{tab.label}</span>
                  </button>
              ))}
          </nav>

          <div className="p-4 border-t border-neutral-800">
              <button onClick={onClose} className="w-full flex items-center justify-center gap-2 p-3 rounded-xl bg-neutral-800 text-neutral-300 hover:bg-neutral-700 hover:text-white transition-colors">
                  <X className="w-5 h-5" />
                  <span className="hidden md:block font-medium">Закрыть</span>
              </button>
          </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 overflow-hidden flex flex-col bg-neutral-950">
          <header className="h-16 border-b border-neutral-800 flex items-center px-8 bg-neutral-900/50">
              <h2 className="text-xl font-bold text-white">
                  {tabs.find(t => t.id === activeTab)?.label} Manager
              </h2>
          </header>

          <div className="flex-1 overflow-y-auto p-6 md:p-10">
              <div className="max-w-6xl mx-auto h-full">
                  
                  {activeTab === 'lessons' && (
                      <div className="space-y-8">
                          <div className="flex justify-between items-center">
                              <p className="text-neutral-400">Настройка контента уроков.</p>
                              <div className="flex gap-2">
                                  <button onClick={repairLessonsTable} className="text-xs flex items-center gap-1 bg-neutral-900 border border-neutral-800 hover:border-red-900 text-neutral-500 hover:text-red-500 px-3 py-2 rounded transition-colors">
                                      <Wrench className="w-3 h-3" /> Fix DB Table
                                  </button>
                                  <div className="text-xs text-neutral-500 bg-neutral-900 border border-neutral-800 px-3 py-2 rounded">
                                      Всего уроков: {lessons.length}
                                  </div>
                              </div>
                          </div>
                          
                          <div className="grid gap-6">
                            {lessons.map((lesson, idx) => (
                                <div key={lesson.id} className="bg-neutral-900/50 p-6 rounded-xl border border-neutral-800 hover:border-neutral-700 transition-colors">
                                     {/* Header */}
                                     <div className="flex justify-between items-center mb-6 pb-2 border-b border-neutral-800">
                                        <div className="flex items-center gap-3">
                                            <div className="w-8 h-8 rounded-full bg-neutral-800 flex items-center justify-center text-sm font-bold text-white border border-neutral-700">
                                                {idx + 1}
                                            </div>
                                            <span className="font-bold text-white text-lg">{lesson.title}</span>
                                        </div>
                                        <span className="text-[10px] font-mono text-neutral-500 uppercase">ID: {lesson.id}</span>
                                     </div>
                                     
                                     <div className="space-y-6">
                                        {/* Row 1: Title & Video */}
                                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                            <div className="space-y-2">
                                                <label className="text-xs font-bold text-neutral-500 uppercase">Название урока</label>
                                                <input 
                                                    type="text" 
                                                    value={lesson.title} 
                                                    onChange={(e) => onUpdateLesson(lesson.id, { title: e.target.value })} 
                                                    className="w-full bg-neutral-950 border border-neutral-800 rounded-lg px-4 py-3 text-white text-sm focus:border-red-600 outline-none transition-colors"
                                                    placeholder="Название..."
                                                />
                                            </div>
                                            <div className="space-y-2">
                                                <label className="text-xs font-bold text-neutral-500 uppercase">Видео (YouTube URL)</label>
                                                <input 
                                                    type="text" 
                                                    value={lesson.video_url} 
                                                    onChange={(e) => onUpdateLesson(lesson.id, { video_url: e.target.value })} 
                                                    className="w-full bg-neutral-950 border border-neutral-800 rounded-lg px-4 py-3 text-white text-sm focus:border-red-600 outline-none transition-colors"
                                                    placeholder="https://youtube.com/..."
                                                />
                                            </div>
                                        </div>

                                        {/* Row 2: Content */}
                                        <div className="space-y-2">
                                            <label className="text-xs font-bold text-neutral-500 uppercase flex justify-between">
                                                <span>Текст под видео</span>
                                                <span className="text-[10px] font-normal opacity-50">Каждый абзац с новой строки</span>
                                            </label>
                                            <textarea 
                                                value={lesson.content?.join('\n') || ''}
                                                onChange={(e) => onUpdateLesson(lesson.id, { content: e.target.value.split('\n') })}
                                                rows={6}
                                                className="w-full bg-neutral-950 border border-neutral-800 rounded-lg px-4 py-3 text-white text-sm focus:border-red-600 outline-none transition-colors resize-y leading-relaxed"
                                                placeholder="Введите текст урока..."
                                            />
                                        </div>

                                        {/* Row 3: Related Articles */}
                                        <div className="space-y-3 bg-black/20 p-4 rounded-lg border border-white/5">
                                            <div className="flex justify-between items-center">
                                                <label className="text-xs font-bold text-neutral-500 uppercase flex items-center gap-2">
                                                    <FileText className="w-3 h-3"/> Карточки статей (Снизу видео)
                                                </label>
                                                <span className="text-[9px] text-neutral-600 italic">Пустые слоты будут заполнены автоматически</span>
                                            </div>
                                            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4">
                                                {[0,1,2,3].map(i => (
                                                    <div key={i} className="space-y-1">
                                                        <span className="text-[10px] text-neutral-400 uppercase font-bold pl-1">Слот #{i+1}</span>
                                                        <div className="relative">
                                                            <select 
                                                                value={lesson.related_articles?.[i] || 0}
                                                                onChange={(e) => {
                                                                    const newIds = [...(lesson.related_articles || [])];
                                                                    // Fill gaps
                                                                    for(let k=0; k<=i; k++) { if(newIds[k] === undefined) newIds[k] = 0; }
                                                                    newIds[i] = parseInt(e.target.value);
                                                                    onUpdateLesson(lesson.id, { related_articles: newIds });
                                                                }}
                                                                className="w-full bg-neutral-950 border border-neutral-800 rounded-lg pl-3 pr-8 py-2.5 text-xs text-white outline-none focus:border-red-600 appearance-none cursor-pointer hover:bg-neutral-900 transition-colors"
                                                            >
                                                                <option value={0} className="text-neutral-500">-- Авто (Случайно) --</option>
                                                                {articles.map(art => (
                                                                    <option key={art.id} value={art.id}>
                                                                        #{art.id} {art.title ? (art.title.length > 20 ? art.title.substring(0,20)+'...' : art.title) : 'Untitled'}
                                                                    </option>
                                                                ))}
                                                            </select>
                                                            <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-neutral-500">
                                                                <ChevronDown className="w-3 h-3" />
                                                            </div>
                                                        </div>
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                     </div>
                                </div>
                            ))}
                          </div>
                      </div>
                  )}

                  {activeTab === 'shop' && <MarketplaceManager products={products} onSave={onRefresh} />}
                  {activeTab === 'courses' && <CourseManager courses={courses} onSave={onRefresh} />}
                  {activeTab === 'catalog' && <CatalogManager categories={catalogCategories} videos={catalogVideos} onSave={onRefresh} />}
                  {activeTab === 'events' && <EventsManager events={events} onSave={onRefresh} />}
                  {activeTab === 'history' && <HistoryManager events={history} onSave={onRefresh} />}
                  {activeTab === 'articles' && <ArticleConstructor articles={articles} onSave={onRefresh} />}
                  {activeTab === 'glossary' && <GlossaryManager dictionary={dictionary} onSave={onRefresh} />}

              </div>
          </div>
      </div>
    </div>
  );
};

export default SettingsModal;
